import { describe, expect, it } from "vitest";
import { matchesCodeownersPattern, parseCodeowners, resolveOwners } from "./codeowners";

const TEXT = `# Code generated by githubgen. DO NOT EDIT.
* @open-telemetry/collector-contrib-approvers

receiver/prometheusreceiver/ @alice @bob
exporter/loggingexporter/ @carol # rotated
.github/CODEOWNERS @maintainers
Makefile
docs/*.md @docs-team
**/generated.go @codegen
`;

describe("parseCodeowners", () => {
  it("skips comments, blank lines and pattern-only rows", () => {
    const rules = parseCodeowners(TEXT);
    expect(rules.map((rule) => rule.pattern)).toEqual([
      "*",
      "receiver/prometheusreceiver/",
      "exporter/loggingexporter/",
      ".github/CODEOWNERS",
      "docs/*.md",
      "**/generated.go",
    ]);
    expect(rules[3].owners).toEqual(["@maintainers"]);
  });
});

describe("matchesCodeownersPattern", () => {
  it("matches everything for the bare catch-all", () => {
    expect(matchesCodeownersPattern("*", "CONTRIBUTING.md")).toBe(true);
    expect(matchesCodeownersPattern("*", "receiver/foo/go.mod")).toBe(true);
  });

  it("treats a trailing slash as a directory prefix without sibling bleed", () => {
    expect(matchesCodeownersPattern("receiver/foo/", "receiver/foo/")).toBe(true);
    expect(matchesCodeownersPattern("receiver/foo/", "receiver/foo/metadata.yaml")).toBe(true);
    expect(matchesCodeownersPattern("receiver/foo/", "receiver/foobar/go.mod")).toBe(false);
    expect(matchesCodeownersPattern("receiver/foo/", "receiver/foo")).toBe(false);
  });

  it("anchors patterns containing a slash to the repository root", () => {
    expect(matchesCodeownersPattern(".github/CODEOWNERS", ".github/CODEOWNERS")).toBe(true);
    expect(matchesCodeownersPattern(".github/CODEOWNERS", "sub/.github/CODEOWNERS")).toBe(false);
  });

  it("matches slash-free patterns at any depth", () => {
    expect(matchesCodeownersPattern("Makefile", "Makefile")).toBe(true);
    expect(matchesCodeownersPattern("Makefile", "receiver/foo/Makefile")).toBe(true);
    expect(matchesCodeownersPattern("Makefile", "Makefile.am")).toBe(false);
    expect(matchesCodeownersPattern("docs", "docs/")).toBe(true);
  });

  it("supports glob wildcards", () => {
    expect(matchesCodeownersPattern("docs/*.md", "docs/testing.md")).toBe(true);
    expect(matchesCodeownersPattern("docs/*.md", "docs/api/testing.md")).toBe(false);
    expect(matchesCodeownersPattern("**/generated.go", "a/b/generated.go")).toBe(true);
  });
});

describe("resolveOwners", () => {
  const rules = parseCodeowners(TEXT);

  it("lets the last matching rule win", () => {
    expect(resolveOwners(rules, "receiver/prometheusreceiver/go.mod")).toEqual(["@alice", "@bob"]);
    expect(resolveOwners(rules, ".github/CODEOWNERS")).toEqual(["@maintainers"]);
    expect(resolveOwners(rules, "docs/testing.md")).toEqual(["@docs-team"]);
  });

  it("falls back to the catch-all and returns nothing when unmatched", () => {
    expect(resolveOwners(rules, "CONTRIBUTING.md")).toEqual([
      "@open-telemetry/collector-contrib-approvers",
    ]);
    expect(resolveOwners([], "CONTRIBUTING.md")).toEqual([]);
  });
});
